#include "WFS210/wfs210_process.h"


VOID InitLowVoltage(VOID)
{
	CM1CONbits.CON = 0;		// comparator is disabled

	CVRCONbits.BGSEL = 1;	// 0.6V Band Gap reference source
	CVRCONbits.CVRR = 1;	// CVRSRC/24 step size
	CVRCONbits.CVR = 5;		// CVREFIN = 5/24 * CVRSRC
	CVRCONbits.VREFSEL = 0;	// CVREFIN is generated by the resistor network
	CVRCONbits.CVROE = 0;	// voltage level is disconnected from CVREF pin
	CVRCONbits.CVRSS = 0;	// CVRSRC = AVDD - AVSS
	CVRCONbits.CVREN = 1;	// comparator voltage reference circuit powered on

	CM1CONbits.CCH = 3;		// Vin- input of comparator connects to IVREF
	CM1CONbits.CREF = 1;	// Vin+ input connects to internal CVREFIN voltage
	CM1CONbits.COE = 0;		// comparator output is internal only
	CM1CONbits.CPOL = 0;	// comparator output is not inverted
	CM1CONbits.EVPOL = 0;	// trigger/event/interrupt generation is disabled
	CM1CONbits.CEVT = 0;	// comparator event did not occur
	CM1CONbits.CON = 1;		// comparator is enabled

	CMSTATbits.CMSIDL = 1;	// discontinues operation of all comparators when device enters Idle mode
}


VOID LowVoltageTask(VOID)
{
	if (CMSTATbits.C1OUT)
	{
		scope_settings.status.flags.low_voltage = FALSE;
	}
	else
	{
		scope_settings.status.flags.low_voltage = TRUE;
	}
}